name: 'setup-shellcheck'
description: 'Install shellcheck and cache it for GitHub Actions'
author: 'pollenJP'

branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  version:
    description: 'shellcheck version'
    required: true
    default: 'latest'
  github-token:
    description: 'GitHub token'
    required: false
    default: ''

runs:
  using: node20
  main: dist/index.js
